const autoBrands = {
  TOYOTA: "Toyota",
  FORD: "Ford",
  CHEVROLET: "Chevrolet",
  HONDA: "Honda",
  VOLKSWAGEN: "Volkswagen",
  NISSAN: "Nissan",
  BMW: "BMW",
  MERCEDES_BENZ: "Mercedes-Benz",
  AUDI: "Audi",
  HYUNDAI: "Hyundai",
  KIA: "Kia",
  SUBARU: "Subaru",
  MAZDA: "Mazda",
  PORSCHE: "Porsche",
  FERRARI: "Ferrari",
  LAMBORGHINI: "Lamborghini",
  ASTON_MARTIN: "Aston Martin",
  JAGUAR: "Jaguar",
  LAND_ROVER: "Land Rover",
  VOLVO: "Volvo",
  TESLA: "Tesla",
  BUICK: "Buick",
  CADILLAC: "Cadillac",
  GMC: "GMC",
  DODGE: "Dodge",
  JEEP: "Jeep",
  CHRYSLER: "Chrysler",
  MITSUBISHI: "Mitsubishi",
  ALFA_ROMEO: "Alfa Romeo",
  LEXUS: "Lexus",
};

export default autoBrands;
